-- Server-only receipts for payment webhooks and push delivery attempts.

create table if not exists public.provider_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text,
  status text not null default 'processing'
    check (status in ('processing', 'succeeded', 'failed', 'ignored')),
  attempt_count integer not null default 1 check (attempt_count > 0),
  last_error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(provider, provider_event_id)
);

create index if not exists provider_webhook_status_updated_idx
  on public.provider_webhook_events (status, updated_at desc);

create table if not exists public.notification_delivery_attempts (
  id bigint generated by default as identity primary key,
  notification_id uuid references public.notifications(id) on delete cascade,
  user_id uuid references public.users(id) on delete cascade,
  subscription_id uuid references public.push_subscriptions(id) on delete set null,
  channel text not null default 'web_push',
  status text not null check (status in ('sent', 'failed', 'stale_removed', 'skipped')),
  provider_status integer,
  error text,
  attempted_at timestamptz not null default now()
);

create index if not exists notification_delivery_status_attempted_idx
  on public.notification_delivery_attempts (status, attempted_at desc);
create index if not exists notification_delivery_notification_idx
  on public.notification_delivery_attempts (notification_id, attempted_at desc);
create unique index if not exists notification_delivery_email_sent_unique_idx
  on public.notification_delivery_attempts (notification_id)
  where channel = 'email' and status = 'sent' and notification_id is not null;
create unique index if not exists notification_delivery_push_sent_unique_idx
  on public.notification_delivery_attempts (notification_id, subscription_id)
  where channel = 'web_push' and status = 'sent' and notification_id is not null and subscription_id is not null;

create unique index if not exists creator_payouts_stripe_invoice_unique_idx
  on public.creator_payouts (stripe_invoice_id);

alter table public.provider_webhook_events enable row level security;
alter table public.notification_delivery_attempts enable row level security;
revoke all on public.provider_webhook_events, public.notification_delivery_attempts from anon, authenticated;
grant all on public.provider_webhook_events, public.notification_delivery_attempts to service_role;

comment on table public.provider_webhook_events is
  'Retry-safe, server-only receipt ledger for billing and commerce webhooks.';
comment on table public.notification_delivery_attempts is
  'Server-only per-device delivery telemetry for push notifications.';
