-- Immutable server-side audit trail for privileged and moderation actions.

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  request_id text,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_actor_created_idx
  on public.admin_audit_logs (actor_user_id, created_at desc);
create index if not exists admin_audit_logs_target_created_idx
  on public.admin_audit_logs (target_type, target_id, created_at desc);
create index if not exists admin_audit_logs_action_created_idx
  on public.admin_audit_logs (action, created_at desc);

alter table public.admin_audit_logs enable row level security;
revoke all on table public.admin_audit_logs from anon, authenticated;
grant all on table public.admin_audit_logs to service_role;

alter table public.reports
  add column if not exists reviewed_at timestamptz,
  add column if not exists resolution_note text;

create index if not exists reports_status_created_idx
  on public.reports (status, created_at desc);

drop policy if exists reports_admin_update on public.reports;

comment on table public.admin_audit_logs is
  'Append-only service-role audit log for administrative and moderation actions.';
