create table if not exists public.product_interaction_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  session_id uuid not null,
  event_name text not null check (event_name in ('route_view', 'route_ready', 'action_success', 'action_failure', 'slow_interaction', 'activation')),
  route text not null check (route ~ '^/[A-Za-z0-9_./@%{}\[\]-]*$' and length(route) between 1 and 180),
  outcome text not null default 'observed' check (outcome in ('observed', 'success', 'failure', 'abandoned')),
  duration_ms integer check (duration_ms is null or duration_ms between 0 and 120000),
  device_class text not null check (device_class in ('phone', 'foldable', 'tablet', 'desktop', 'wide')),
  created_at timestamptz not null default now()
);

create index if not exists product_interaction_events_recent_idx
  on public.product_interaction_events(created_at desc);
create index if not exists product_interaction_events_route_recent_idx
  on public.product_interaction_events(route, created_at desc);
create index if not exists product_interaction_events_failure_recent_idx
  on public.product_interaction_events(event_name, created_at desc)
  where outcome = 'failure' or event_name = 'slow_interaction';

alter table public.product_interaction_events enable row level security;

create policy "Admins read product interaction telemetry"
on public.product_interaction_events for select to authenticated
using (
  exists (
    select 1 from public.users member
    where member.id = (select auth.uid()) and member.account_type = 'admin'
  )
);

revoke all on public.product_interaction_events from public, anon, authenticated;
grant select on public.product_interaction_events to authenticated;

create or replace function public.record_product_interaction(
  p_session_id uuid,
  p_event_name text,
  p_route text,
  p_outcome text,
  p_duration_ms integer,
  p_device_class text
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_now timestamptz := now();
  v_count integer;
  v_rate_key text := 'product-telemetry:' || p_session_id::text;
begin
  if p_event_name not in ('route_view', 'route_ready', 'action_success', 'action_failure', 'slow_interaction', 'activation') then return false; end if;
  if p_outcome not in ('observed', 'success', 'failure', 'abandoned') then return false; end if;
  if p_device_class not in ('phone', 'foldable', 'tablet', 'desktop', 'wide') then return false; end if;
  if p_route is null or length(p_route) not between 1 and 180 or p_route !~ '^/[A-Za-z0-9_./@%{}\[\]-]*$' then return false; end if;
  if p_duration_ms is not null and p_duration_ms not between 0 and 120000 then return false; end if;

  insert into public.rate_limit_counters as counters (key, window_start, count)
  values (v_rate_key, v_now, 1)
  on conflict (key) do update set
    window_start = case when counters.window_start < v_now - interval '1 day' then v_now else counters.window_start end,
    count = case when counters.window_start < v_now - interval '1 day' then 1 else least(counters.count + 1, 121) end
  returning count into v_count;
  if v_count > 120 then return false; end if;

  insert into public.product_interaction_events(user_id, session_id, event_name, route, outcome, duration_ms, device_class)
  values (auth.uid(), p_session_id, p_event_name, p_route, p_outcome, p_duration_ms, p_device_class);
  return true;
end;
$$;

revoke all on function public.record_product_interaction(uuid, text, text, text, integer, text) from public;
grant execute on function public.record_product_interaction(uuid, text, text, text, integer, text) to anon, authenticated;
