create table if not exists public.nfl_odds_current (
  game_id text primary key,
  bdl_game_id bigint not null,
  season integer not null,
  week integer not null,
  away_abbr text not null,
  home_abbr text not null,
  board jsonb not null,
  payload_hash text not null,
  captured_at timestamptz not null default now()
);

create table if not exists public.nfl_odds_snapshot_history (
  id bigint generated by default as identity primary key,
  game_id text not null,
  bdl_game_id bigint not null,
  season integer not null,
  week integer not null,
  away_abbr text not null,
  home_abbr text not null,
  board jsonb not null,
  payload_hash text not null,
  captured_at timestamptz not null default now()
);

create index if not exists nfl_odds_history_game_time_idx
  on public.nfl_odds_snapshot_history (game_id, captured_at desc);
create index if not exists nfl_odds_history_bdl_time_idx
  on public.nfl_odds_snapshot_history (bdl_game_id, captured_at desc);

comment on table public.nfl_odds_current is
  'Server-only latest BALLDONTLIE NFL GOAT game odds and player props for TheSideline.';
comment on table public.nfl_odds_snapshot_history is
  'Append-only changed NFL odds snapshots. Preserves markets that BALLDONTLIE removes near game completion.';

alter table public.nfl_odds_current enable row level security;
alter table public.nfl_odds_snapshot_history enable row level security;
revoke all on table public.nfl_odds_current from anon, authenticated;
revoke all on table public.nfl_odds_snapshot_history from anon, authenticated;
revoke all on sequence public.nfl_odds_snapshot_history_id_seq from anon, authenticated;
