-- Keep trigger/service settlement helpers unreachable from the public API,
-- and make every user-callable role RPC explicit rather than inherited.
revoke all on function public.apply_sport_leg_result_to_post(uuid, text, text, text) from public, anon, authenticated;
grant execute on function public.apply_sport_leg_result_to_post(uuid, text, text, text) to service_role;

revoke all on function public.sync_message_reaction_count() from public, anon, authenticated;

revoke all on function public.set_group_member_role(uuid, uuid, text) from public, anon;
grant execute on function public.set_group_member_role(uuid, uuid, text) to authenticated;

revoke all on function public.remove_group_member(uuid, uuid) from public, anon;
grant execute on function public.remove_group_member(uuid, uuid) to authenticated;

-- Read cursors are frequently joined and cleaned up by channel/partner.
-- A durable identity also makes support/audit tooling unambiguous.
alter table public.message_read_positions
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.message_read_positions'::regclass
      and contype = 'p'
  ) then
    alter table public.message_read_positions
      add constraint message_read_positions_pkey primary key (id);
  end if;
end
$$;

create index if not exists message_read_positions_channel_idx
  on public.message_read_positions(channel_id)
  where channel_id is not null;
create index if not exists message_read_positions_partner_idx
  on public.message_read_positions(partner_id)
  where partner_id is not null;
