create table if not exists public.nfl_pikkit_picks_current (
  game_id text primary key,
  game_date date not null,
  season integer not null,
  week integer not null,
  away_abbr text not null,
  home_abbr text not null,
  snapshot jsonb not null,
  payload_hash text not null,
  captured_at timestamptz not null default now()
);

create table if not exists public.nfl_pikkit_picks_snapshot_history (
  id bigint generated by default as identity primary key,
  game_id text not null,
  game_date date not null,
  season integer not null,
  week integer not null,
  away_abbr text not null,
  home_abbr text not null,
  snapshot jsonb not null,
  payload_hash text not null,
  captured_at timestamptz not null default now(),
  unique (game_id, payload_hash)
);

create index if not exists nfl_pikkit_current_date_idx
  on public.nfl_pikkit_picks_current (game_date, game_id);
create index if not exists nfl_pikkit_history_game_time_idx
  on public.nfl_pikkit_picks_snapshot_history (game_id, captured_at desc);
create index if not exists nfl_pikkit_history_date_idx
  on public.nfl_pikkit_picks_snapshot_history (game_date, game_id, captured_at desc);

comment on table public.nfl_pikkit_picks_current is
  'Server-only latest Pikkit NFL public-pick snapshot for The Sideline.';
comment on table public.nfl_pikkit_picks_snapshot_history is
  'Append-only changed Pikkit NFL public-pick snapshots aligned to The Sideline market story.';

alter table public.nfl_pikkit_picks_current enable row level security;
alter table public.nfl_pikkit_picks_snapshot_history enable row level security;
revoke all on table public.nfl_pikkit_picks_current from anon, authenticated;
revoke all on table public.nfl_pikkit_picks_snapshot_history from anon, authenticated;
revoke all on sequence public.nfl_pikkit_picks_snapshot_history_id_seq from anon, authenticated;
