create table if not exists public.pipeline_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  run_id uuid not null default gen_random_uuid(),
  status text not null check (status in ('running', 'succeeded', 'failed')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint check (duration_ms is null or duration_ms >= 0),
  http_status integer check (http_status is null or http_status between 100 and 599),
  records_processed integer check (records_processed is null or records_processed >= 0),
  error text,
  details jsonb not null default '{}'::jsonb,
  constraint pipeline_runs_job_run_unique unique (job_name, run_id)
);

create index if not exists pipeline_runs_job_started_idx
  on public.pipeline_runs (job_name, started_at desc);

create index if not exists pipeline_runs_failed_started_idx
  on public.pipeline_runs (started_at desc)
  where status = 'failed';

alter table public.pipeline_runs enable row level security;

revoke all on table public.pipeline_runs from anon, authenticated;
grant all on table public.pipeline_runs to service_role;

comment on table public.pipeline_runs is
  'Server-only execution ledger for scheduled and manually invoked production pipelines.';
