import assert from 'node:assert/strict'
import { chromium } from 'playwright-core'
import { mkdir } from 'node:fs/promises'
const browser=await chromium.launch()
await mkdir('.artifacts/mobile-research',{recursive:true})
try {
  for(const width of [320,390,549,768,1024]){
    const page=await browser.newPage({viewport:{width,height:850},hasTouch:true})
    const errors:string[]=[]
    page.on('pageerror',e=>errors.push(e.message))
    await page.goto('http://127.0.0.1:4189/dugout')
    const trigger=page.getByRole('button',{name:'Choose sport and research tools'})
    await trigger.click()
    const sheet=page.getByRole('dialog',{name:'Research',exact:true})
    await sheet.waitFor()
    await sheet.evaluate(node => Promise.all(node.getAnimations().map(animation => animation.finished)))
    assert.equal(await sheet.locator('a').first().innerText(),'NFL\nThe Sideline')
    assert.equal(await page.evaluate(()=>document.body.style.overflow),'hidden')
    assert.equal(await sheet.evaluate(node=>node.scrollWidth<=node.clientWidth),true)
    const box=await sheet.boundingBox()
    assert(box && box.x>=0 && box.x+box.width<=width && box.y>=0 && box.y+box.height<=851, JSON.stringify(box))
    await sheet.getByRole('button',{name:'NFL tools',exact:true}).click()
    assert.equal(await sheet.getByRole('navigation',{name:'NFL quick tools'}).locator('a').count(),4)
    await page.screenshot({path:`.artifacts/mobile-research/nfl-${width}.png`})
    await sheet.getByRole('link',{name:'NFL The Sideline',exact:true}).click()
    await sheet.waitFor({state:'detached'})
    assert.match(page.url(),/the-sideline/)
    assert.notEqual(await page.evaluate(()=>document.body.style.overflow),'hidden')
    await page.goto('http://127.0.0.1:4189/the-sideline?game=2026_03_ATL_GB&date=2026-09-24&sample=regular')
    await trigger.click()
    await sheet.getByRole('link',{name:'Cheatsheets',exact:true}).click()
    assert.match(page.url(),/game=2026_03_ATL_GB/)
    assert.match(page.url(),/mode=cheatsheets/)
    await sheet.waitFor({state:'detached'})
    await trigger.click()
    await page.keyboard.press('Escape')
    await sheet.waitFor({state:'detached'})
    assert.equal(await trigger.evaluate(el=>el===document.activeElement),true,'focus restored')
    await trigger.click()
    await sheet.getByRole('button',{name:'MLB tools',exact:true}).click()
    await sheet.getByRole('link',{name:'Spray Charts',exact:true}).scrollIntoViewIfNeeded()
    await sheet.getByRole('button',{name:'Close research menu'}).click()
    assert.notEqual(await page.evaluate(()=>document.body.style.overflow),'hidden')
    await page.goto('http://127.0.0.1:4189/feed?access=no')
    await trigger.click()
    assert.equal(await sheet.getByRole('button',{name:'NFL tools',exact:true}).count(),0)
    assert.equal(await sheet.locator('a[href*="the-sideline"]').count(),0)
    await page.keyboard.press('Escape')
    assert.deepEqual(errors,[])
    console.log(`${width}px PASS sport boards, tools, context, modal scroll, Escape/focus, access, containment`)
    await page.close()
  }
} finally {await browser.close()}
