import { chromium } from 'playwright-core'
import assert from 'node:assert/strict'
const browser = await chromium.launch()
try {
  for (const width of [390, 768, 1280]) {
    const page = await browser.newPage({ viewport: { width, height: 900 } })
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('http://127.0.0.1:4187/props')
    await page.addStyleTag({ content: ':root { --layer-modal:500; --bg:#05070A; --surface:#0B0E13; --surface-2:#101923; --text-1:#edf4fc; --text-3:#9aa9bd; --accent:#b4ff4d; --accent-fg:#071006; --border:#253343; }' })
    await page.getByRole('button', { name: 'Save Bijan Robinson 10+ Receiving Yards fanduel', exact: true }).click()
    await page.getByRole('button', { name: 'Remove Bijan Robinson 10+ Receiving Yards fanduel', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Review Bijan Robinson 10+ Receiving Yards for posting', exact: true }).click()
    await page.getByRole('dialog', { name: '★ My Watchlist' }).waitFor()
    await page.getByRole('button', { name: 'Post', exact: true }).click()
    const post = page.getByRole('dialog', { name: 'Post Pick', exact: true })
    await post.waitFor()
    assert.equal(await post.getByText('10+ Receiving Yards', { exact: true }).count(), 1)
    await post.getByRole('button', { name: 'Post Pick', exact: true }).click()
    const payload = await page.evaluate(() => (window as any).postedPayload)
    assert.equal(payload.sport, 'NFL')
    assert.equal(payload.legs[0].player_id, 'bdl:1')
    assert.equal(payload.legs[0].numeric_line, 10)
    assert.equal(payload.legs[0].odds, 110)
    await page.getByRole('button', { name: 'Close watchlist' }).click()
    await page.getByText('Display Options', { exact: true }).click()
    await page.getByLabel('Line Type', { exact: true }).selectOption('over_under')
    await page.getByLabel('Side', { exact: true }).selectOption('under')
    await page.getByRole('button', { name: 'Save Bijan Robinson Under 10 Receiving Yards fanduel', exact: true }).click()
    await page.getByRole('button', { name: 'Remove Bijan Robinson Under 10 Receiving Yards fanduel', exact: true }).waitFor()
    const matrix = { id: 'fixture-matrix', name: 'TD Watch', color: '#a7ff3f', priority: 0, enabled: true, matrix_type: 'classic', match_mode: 'all', match_any_count: null, pipeline_scope: null, element_code: 'NFL-TEST1234', definition: { factors: [{ id: 'factor', category: 'market', field: 'odds', operator: 'gte', value: 600, window: 'season', vendor: 'fanduel', propType: 'anytime_td', marketValue: 'current', marketSide: 'over', marketKind: 'milestone' }] } }
    await page.route('**/api/nfl-matrices', route => route.fulfill({ json: { matrices: [matrix] } }))
    await page.route('**/api/nfl-matrices/fixture-matrix', async route => {
      Object.assign(matrix, route.request().postDataJSON())
      await route.fulfill({ json: { id: matrix.id } })
    })
    await page.goto('http://127.0.0.1:4187/')
    await page.getByRole('button', { name: 'Matrices', exact: true }).click()
    await page.getByRole('dialog', { name: 'NFL Matrices', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Disable TD Watch', exact: true }).click()
    await page.getByRole('button', { name: 'Enable TD Watch', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Enable TD Watch', exact: true }).click()
    await page.getByRole('button', { name: 'Disable TD Watch', exact: true }).waitFor()
    await page.getByRole('button', { name: 'Edit', exact: true }).click()
    await page.getByRole('dialog', { name: 'NFL Matrix editor' }).waitFor()
    await page.getByLabel('Name', { exact: true }).fill('TD Watch Edited')
    await page.getByRole('button', { name: 'Save NFL Matrix', exact: true }).click()
    await page.getByRole('dialog', { name: 'NFL Matrices', exact: true }).waitFor()
    await page.keyboard.press('Escape')
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    await page.getByLabel('Active matrix matches').getByRole('button', { name: /TD Watch/ }).waitFor()
    assert.ok(await page.locator('td').getByText('TD Watch Edited', { exact: true }).count() > 0)
    assert.equal(await page.evaluate(() => document.body.style.overflow), '')
    assert.deepEqual(errors, [])
    await page.screenshot({ path: `.artifacts/nfl-social-${width}.png`, fullPage: false })
    console.log(`PASS ${width}: exact ladder save/remove, NFL post payload, under, matrix modal/Escape, zero JS errors`)
    await page.close()
  }
} finally { await browser.close() }
