// Synthetic local-only UI fixture. No account access or production writes.
import { createServer } from 'node:http'
import { build } from 'esbuild'
const players = ['Receiver One', 'Receiver Two', 'Running Back'].map((name, i) => ({ id: i + 1, name, team: 'BUF', position: 'WR', markets: [40, 50, 60, 70].map(line => ({ key: `yards:${line}`, propType: 'receiving_yards', category: 'receiving', label: 'Receiving yards', line, offers: [{ vendor: 'fanduel', line, type: 'milestone', current: { odds: 240 }, updatedAt: null }] })), publicPicks: [{ propType: 'receiving_yards', label: '50+ Receiving yards', rawMarket: '50+ Receiving yards', line: 50, kind: 'milestone', picks: 40 - i, capturedAt: '2026-09-20T16:00:00Z' }] }))
const board = { players, bdlGameId: 1, status: 'ready', source: 'snapshot', capturedAt: null, gameLines: [] }
const results = { status: 'in_progress', updatedAt: '2026-09-20T19:00:00Z', firstTd: null, firstTdKnown: false, players: players.map((p, i) => ({ ...p, stats: { receiving_yards: [43, 70, 0][i] } })) }
const bundle = await build({ stdin: { resolveDir: process.cwd(), loader: 'tsx', contents: `import {createRoot} from 'react-dom/client';import {SidelineResearchClient} from './src/app/the-sideline/SidelineResearchClient';createRoot(document.getElementById('root')).render(<SidelineResearchClient board={${JSON.stringify(board)}} initialResults={{...${JSON.stringify(results)},status:location.search.includes('final')?'final':'in_progress'}} mode="public" boardHref="/" title="Synthetic result verification" teams={[{abbr:'BUF',name:'Buffalo',color:'#123456',logo:null}]}/>);` }, bundle: true, write: false, outdir: '.artifacts/public-fixture', platform: 'browser', jsx: 'automatic', define: { 'process.env.NODE_ENV': '"development"' }, plugins: [{ name: 'next-fixture', setup(builder) { builder.onResolve({ filter: /^next\/(image|link)$/ }, args => ({ path: args.path, namespace: 'stub' })); builder.onLoad({ filter: /.*/, namespace: 'stub' }, args => ({ contents: args.path === 'next/link' ? 'export default function Link({prefetch,...p}){return <a {...p}/>}' : 'export default function Image({unoptimized,...p}){return <img {...p}/>} ', loader: 'tsx', resolveDir: process.cwd() })) } }] })
createServer((req, res) => {
  const ext = req.url?.split('.').pop()
  if (ext === 'js' || ext === 'css') { res.setHeader('content-type', ext === 'js' ? 'text/javascript' : 'text/css'); res.end(bundle.outputFiles.find(file => file.path.endsWith('.' + ext))?.text); return }
  res.setHeader('content-type', 'text/html')
  res.end('<html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><style>*{box-sizing:border-box}body{margin:0;font-family:Arial;background:#080c12}button,input,select{font:inherit}</style></head><body><main id="root"></main><script src="/app.js"></script></body></html>')
}).listen(4188, '127.0.0.1', () => console.log('Public fixture http://127.0.0.1:4188'))
