// Synthetic local harness: real production UI, mocked auth/data; never publishes.
import { createServer } from 'node:http'
import { build } from 'esbuild'
const mocks: Record<string,string> = {
  'next/navigation': 'export const useRouter=()=>({push(){},refresh(){},replace(){}})',
  'next/link': 'export default function Link(p){return <a {...p}/>}',
  'next/image': 'export default function Image({fill,priority,unoptimized,...p}){return <img {...p}/>}',
  '@/context/AuthContext': 'const user={id:"fixture-user"};export const useAuth=()=>({user})',
  '@/lib/supabase/client': `const posts=[{id:'upcoming',created_at:'2026-09-27T10:00:00Z',post_type:'pick',content:'Saved yesterday for Monday',pick_data:{result:'pending',game_date:'2026-09-28'}},{id:'settled',created_at:'2026-09-20T10:00:00Z',post_type:'pick',content:'Past settled pick',pick_data:{result:'win'}}];export function createClient(){return {auth:{getUser:async()=>({data:{user:{id:'fixture-user'}}})},channel:()=>{const c={on:()=>c,subscribe:()=>c};return c},removeChannel(){},from(table){let active=false;let insert=null;const q={select:()=>q,eq:()=>q,in:()=>q,order:()=>q,limit:()=>q,or:()=>{active=true;return q},insert(value){insert=value;return q},single:()=>q,then(resolve){if(insert){window.fixtureWrites=[...(window.fixtureWrites||[]),{table,value:insert}];resolve({data:{id:'created'},error:null});return}resolve({data:table==='research_workspaces'?[{id:'workspace',name:'NFL Research',user_id:'fixture-user'}]:table==='posts'?posts.filter(p=>!active||p.pick_data.result==='pending'):[],error:null})}};return q}}}`,
  '@/components/social/PostCardClient': 'export function PostCardClient({post}){return <article>{post.content}</article>}',
  '@/context/WatchlistContext': `import {useSyncExternalStore} from 'react';let items=[];const listeners=new Set();export function useWatchlist(){useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>items);return {items,signedIn:true,loading:false,pendingCount:items.length,add:async item=>{items=[...items,{...item,id:'11111111-1111-4111-8111-111111111111',status:'pending'}];listeners.forEach(fn=>fn())},remove:async id=>{items=items.filter(i=>i.id!==id);listeners.forEach(fn=>fn())},postBet:async()=>({postId:'test'})}}`,
}
const entry = `import {createRoot} from 'react-dom/client';import {useState} from 'react';import {NflSlateEdgeOverlay} from './src/app/the-sideline/NflSlateEdgeOverlay';import {WatchlistButton} from './src/components/dugout/WatchlistPanel';import {MyPicksButton} from './src/components/dugout/MyPicksPanel';function App(){const [open,setOpen]=useState(location.pathname==='/slate');return <><button onClick={()=>setOpen(true)}>Open Slate Edge</button><NflSlateEdgeOverlay open={open} date="2026-09-28" sample="season" onClose={()=>setOpen(false)}/><WatchlistButton/><MyPicksButton/></>};createRoot(document.getElementById('root')).render(<App/>);`
const result = await build({stdin:{contents:entry,loader:'tsx',resolveDir:process.cwd()},bundle:true,write:false,outdir:'.artifacts/research-flows',platform:'browser',format:'iife',jsx:'automatic',tsconfig:'tsconfig.json',define:{'process.env.NODE_ENV':'"development"'},plugins:[{name:'mock-boundaries',setup(build){build.onResolve({filter:/^(next\/(navigation|image|link)|@\/context\/(AuthContext|WatchlistContext)|@\/lib\/supabase\/client|@\/components\/social\/PostCardClient)$/},a=>({path:a.path,namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:mocks[a.path],loader:'tsx',resolveDir:process.cwd()}))}}]})
const css = `:root{--layer-modal:500;--layer-floating:100;--bg:#05070a;--surface:#0b0e13;--surface-2:#101923;--text-1:#edf4fc;--text-2:#bac7d8;--text-3:#9aa9bd;--accent:#b4ff4d;--accent-fg:#071006;--border:#253343;--border-2:#354453}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text-1);font:14px Arial}button,a{color:inherit}button{background:var(--surface);border:1px solid var(--border);cursor:pointer}a{text-decoration:none}`
createServer((req,res)=>{if(req.url==='/app.js'){res.setHeader('content-type','text/javascript');res.end(result.outputFiles.find(f=>f.path.endsWith('.js'))!.text);return}if(req.url==='/app.css'){res.setHeader('content-type','text/css');res.end(css+result.outputFiles.find(f=>f.path.endsWith('.css'))!.text);return}res.setHeader('content-type','text/html');res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><main id="root"></main><script src="/app.js"></script>')}).listen(4199,'127.0.0.1',()=>console.log('Research flow fixture http://127.0.0.1:4199 — synthetic only'))
