import { createClient } from '@/lib/supabase/server'
import { Bell, Search } from 'lucide-react'
import Link from 'next/link'

export const dynamic = 'force-dynamic'

const TYPES = ['follow', 'reaction', 'comment', 'mention', 'pick_result', 'subscription', 'message', 'repost', 'group_invite', 'new_pick']

export default async function AdminNotificationsPage({
  searchParams,
}: { searchParams: Promise<{ type?: string; q?: string; from?: string; to?: string }> }) {
  const { type, q, from, to } = await searchParams
  const supabase = await createClient()

  // "q" matches either the recipient or the actor — a moderator chasing a
  // specific user's report needs both directions ("what got sent to them"
  // and "what did they trigger for someone else").
  let matchedUserIds: string[] | null = null
  if (q) {
    const { data } = await supabase.from('users').select('id').or(`username.ilike.%${q}%,display_name.ilike.%${q}%`)
    matchedUserIds = (data ?? []).map((u: any) => u.id)
  }

  let query = supabase
    .from('notifications')
    .select('id, type, message, body, read, created_at, user:users!notifications_user_id_fkey(username), actor:users!notifications_actor_id_fkey(username)')
    .order('created_at', { ascending: false })
    .limit(200)

  if (type) query = query.eq('type', type)
  if (from) query = query.gte('created_at', from)
  if (to) query = query.lte('created_at', `${to}T23:59:59`)
  if (q) {
    const idList = matchedUserIds?.length ? matchedUserIds.join(',') : '00000000-0000-0000-0000-000000000000'
    query = query.or(`user_id.in.(${idList}),actor_id.in.(${idList})`)
  }

  const { data: notifications } = await query

  const qs = (overrides: Record<string, string | undefined>) => {
    const params = new URLSearchParams()
    const merged = { type, q, from, to, ...overrides }
    for (const [k, v] of Object.entries(merged)) if (v) params.set(k, v)
    const s = params.toString()
    return s ? `?${s}` : ''
  }

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center gap-3 mb-2">
        <Bell size={20} className="text-zinc-400" />
        <h1 className="text-xl font-black text-white">Notifications</h1>
      </div>
      <p className="text-xs text-zinc-500 mb-6">
        Read-only feed of the last 200 matching notifications. There's no broadcast/compose tool yet — each row is a per-user notification generated by an action (follow, reaction, etc.), not a system-wide message.
      </p>

      {/* Filters */}
      <form className="flex flex-wrap items-end gap-3 mb-4">
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1">User</label>
          <Search size={14} className="absolute left-3 top-1/2 mt-1 -translate-y-1/2 text-zinc-500" />
          <input name="q" defaultValue={q} placeholder="Recipient or actor…"
            className="w-full bg-zinc-900 border border-zinc-800 rounded-xl pl-9 pr-4 py-2 text-sm text-white placeholder:text-zinc-600 outline-none focus:border-green-500/50" />
        </div>
        <div>
          <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1">From</label>
          <input type="date" name="from" defaultValue={from}
            className="bg-zinc-900 border border-zinc-800 rounded-xl px-3 py-2 text-sm text-white outline-none focus:border-green-500/50" />
        </div>
        <div>
          <label className="block text-[10px] font-bold text-zinc-500 uppercase tracking-wider mb-1">To</label>
          <input type="date" name="to" defaultValue={to}
            className="bg-zinc-900 border border-zinc-800 rounded-xl px-3 py-2 text-sm text-white outline-none focus:border-green-500/50" />
        </div>
        {type && <input type="hidden" name="type" value={type} />}
        <button type="submit" className="bg-zinc-800 hover:bg-zinc-700 text-white text-sm font-bold px-4 py-2 rounded-xl transition-colors">
          Apply
        </button>
        {(q || from || to || type) && (
          <Link href="/admin/notifications" className="text-xs font-bold text-zinc-500 hover:text-white px-2 py-2">Clear</Link>
        )}
      </form>

      <div className="flex flex-wrap gap-1 mb-4">
        <Link href={qs({ type: undefined })} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${!type ? 'bg-zinc-800 text-white' : 'text-zinc-500 hover:text-white hover:bg-zinc-800/60'}`}>All types</Link>
        {TYPES.map(t => (
          <Link key={t} href={qs({ type: t })} className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${type === t ? 'bg-zinc-800 text-white' : 'text-zinc-500 hover:text-white hover:bg-zinc-800/60'}`}>{t}</Link>
        ))}
      </div>

      {(notifications?.length ?? 0) === 0 ? (
        <div className="text-center py-20 text-zinc-500 text-sm">No notifications match these filters</div>
      ) : (
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl divide-y divide-zinc-800">
          {(notifications ?? []).map((n: any) => (
            <div key={n.id} className="px-4 py-3 flex items-center gap-3">
              <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${n.read ? 'bg-zinc-700' : 'bg-blue-400'}`} />
              <span className="text-[10px] font-bold bg-zinc-800 text-zinc-400 px-2 py-0.5 rounded-full shrink-0">{n.type}</span>
              <p className="text-xs text-zinc-300 flex-1 min-w-0 truncate">
                {n.actor?.username ? `@${n.actor.username}` : 'System'} → @{n.user?.username ?? '?'}
                {(n.message || n.body) && <span className="text-zinc-500"> · {n.message || n.body}</span>}
              </p>
              <span className="text-xs text-zinc-600 shrink-0">{new Date(n.created_at).toLocaleString()}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
