import { createClient } from '@/lib/supabase/server'
import { Bell } from 'lucide-react'

export const dynamic = 'force-dynamic'

export default async function AdminNotificationsPage() {
  const supabase = await createClient()
  const { data: notifications } = await supabase
    .from('notifications')
    .select('id, type, message, body, read, created_at, user:users!notifications_user_id_fkey(username), actor:users!notifications_actor_id_fkey(username)')
    .order('created_at', { ascending: false })
    .limit(100)

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center gap-3 mb-2">
        <Bell size={20} className="text-zinc-400" />
        <h1 className="text-xl font-black text-white">Notifications</h1>
      </div>
      <p className="text-xs text-zinc-500 mb-6">
        Read-only feed of the last 100 notifications sent. There's no broadcast/compose tool yet — each row is a per-user notification generated by an action (follow, reaction, etc.), not a system-wide message.
      </p>

      {(notifications?.length ?? 0) === 0 ? (
        <div className="text-center py-20 text-zinc-500 text-sm">No notifications yet</div>
      ) : (
        <div className="bg-zinc-900 border border-zinc-800 rounded-xl divide-y divide-zinc-800">
          {(notifications ?? []).map((n: any) => (
            <div key={n.id} className="px-4 py-3 flex items-center gap-3">
              <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${n.read ? 'bg-zinc-700' : 'bg-blue-400'}`} />
              <span className="text-[10px] font-bold bg-zinc-800 text-zinc-400 px-2 py-0.5 rounded-full shrink-0">{n.type}</span>
              <p className="text-xs text-zinc-300 flex-1 min-w-0 truncate">
                {n.message || n.body || `${n.actor?.username ? '@' + n.actor.username : 'System'} → @${n.user?.username}`}
              </p>
              <span className="text-xs text-zinc-600 shrink-0">{new Date(n.created_at).toLocaleString()}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
